language: scala
script: ./tools/travis-script.sh
branches:
  only:
    - master
    - scalacheck2
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com

scala:
  - 2.10.5
  - 2.11.6
jdk:
  - openjdk7
env:
  - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=1
  - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=4
  - PLATFORM=jvm SBT_PARALLEL=false WORKERS=4
  - PLATFORM=js  SBT_PARALLEL=true  WORKERS=1
matrix:
  include:
    - scala: 2.12.0-M1
      jdk: openjdk7
      env: PLATFORM=jvm SBT_PARALLEL=true WORKERS=4
