language: scala
script: ./tools/travis-script.sh
env:
  - PLATFORM=jvm SBT_PARALLEL=yes WORKERS=1 TESTS=1000
  - PLATFORM=jvm SBT_PARALLEL=yes WORKERS=4 TESTS=1000
  - PLATFORM=jvm SBT_PARALLEL=no  WORKERS=4 TESTS=1000
  - PLATFORM=js  SBT_PARALLEL=yes WORKERS=1 TESTS=100
scala:
  - 2.10.5
  - 2.11.6
jdk:
  - openjdk7
matrix:
  include:
    - scala: 2.12.0-M1
      jdk: openjdk7
      env: PLATFORM=jvm SBT_PARALLEL=yes WORKERS=4 TESTS=1000
branches:
  only:
    - master
    - scalacheck2
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com
