language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION $PLATFORM/clean $PLATFORM/update $PLATFORM/compile "$PLATFORM/testOnly * -- -s $TESTS -w $WORKERS"
env:
  - PLATFORM=jvm TESTS=1000 WORKERS=1
  - PLATFORM=jvm TESTS=1000 WORKERS=4
  - PLATFORM=js TESTS=20 WORKERS=1
scala:
  - 2.10.4
  - 2.11.5
jdk:
  - openjdk7
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com

# if we get weird timeouts, see https://github.com/spray/spray/pull/233
# 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)'
