language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION "set scalaJSStage in Global := FastOptStage" $PLATFORM/clean $PLATFORM/update $PLATFORM/compile "$PLATFORM/testOnly * -- -s $TESTS -w $WORKERS" $PLATFORM/mimaReportBinaryIssues
env:
  - PLATFORM=jvm TESTS=1000 WORKERS=1
  - PLATFORM=jvm TESTS=1000 WORKERS=4
  - PLATFORM=js TESTS=20 WORKERS=1
scala:
  - 2.10.5
  - 2.11.6
jdk:
  - openjdk7
branches:
  only:
    - master
    - scalacheck2
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com

# if we get weird timeouts, see https://github.com/spray/spray/pull/233
# 'set concurrentRestrictions in Global += Tags.limit(Tags.Test, 1)'
