language: scala
script: ./tools/travis-script.sh
after_success: ./tools/travis-deploy.sh
branches:
  only:
    - master
    - scalacheck2
notifications:
  email:
    - adriaan.moors@typesafe.com
    - rickynils@gmail.com

scala:
  - 2.10.5
  - 2.11.6
jdk:
  - openjdk8
env:
  global:
    - secure: PwIb1un8vuuyoidnjHaKO81FD49n5ZTVEnf6hVKkMRe3hipr+WGWv19m92yE/n34ROFo1BM9DmfYxaexlE0pI2o/a5MV1i3kNSwUk+Yt8uU6F4+nyQKROQUe76UtAtXmsYgLqXaWSW0+EVidMyhSktkXXxiU5wCGLdKkPu3Vj9w=
    - secure: KeZRD91oE4UzwhSJfjllkwNXnerDGQJSIOuRLVtbLCq0JJnAfj6B7fvI2KyZqQwuhYrUyYOSbSLd6BAi75bBYMb3D1yNdyPA5gHDg5aj96ALojrOuU60+/dOQ0Rg6Pf2UiTlFAXzz1mud8+Q3svaeKX4JDVxj329T3ReBspjyBY=
  matrix:
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
    - PLATFORM=jvm SBT_PARALLEL=true  WORKERS=4 DEPLOY=false
    - PLATFORM=jvm SBT_PARALLEL=false WORKERS=4 DEPLOY=false
    - PLATFORM=js  SBT_PARALLEL=true  WORKERS=1 DEPLOY=true
matrix:
  include:
    - scala: 2.12.0-M2
      jdk: openjdk8
      env: PLATFORM=jvm SBT_PARALLEL=true WORKERS=4 DEPLOY=true
sudo: false
